sudo: false
language: python

install:
  - pip install tox

matrix:
  include:
    - stage: test
      python: 2.7
      env: TOX_ENV=py27-test
    - stage: test
      python: 3.4
      env: TOX_ENV=py34-test
    - stage: test
      python: 3.5
      env: TOX_ENV=py35-test
    - stage: test
      python: 3.6
      env: TOX_ENV=py36-test
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        server: https://test.pypi.org/legacy/
        user: mattbennett
        password:
          secure: "LhN2C1/JTv4mjwq1SislnS1ikcd7NT1k6gefxunBM4t2L+TOSTzXWMXD1aDpq8DHRHCGs3/z2hNywYn8T3Du92VAuqzT+PjJnzPX+p+U3dFdaGQJD4GPiFws6/Wa4XMejFqhK9V+YHaJRqDxSUfWVsRSssd5XdmpJsgVdasCVkesJT9FroD2bLhHvtHNT8yXBAT0wX6TJHMmBYmfMmXd7uXX/dHvo5oYA6sr59p3qQT6dp5uNZ2S/z8IHrWIryY0/g2+HJl1+PL2EowOTNWRA9R5MY0e2yvrSv1V8fpAFMBN8gVPa20fGyRsk6eyWPwjg+Iv9vlZ2zc0kbwyDkOPqOAgHtqUe7LPpGnIAoEfu86nOl8ZT05n49Td3U9cGGoBuJlfpliqv9BWyQuQkntqHcwpSCnra7lfDBdiEzYiL9LzDjTeFbe7LVQqPK8SclGded3aD5TQF8LCQ0k5lbhxC0oygrqAGOQhF4XU7ZUkCK9BisPml3E1H15yYhUF4DfkeNSJH73SfDaQI6oQDWQ9fh+9ooNoBGzeEiXTpuZdeO8GIlQ0yHVRXxRv9laO4nhq1l2k0alrjHUuYKdmExM0qeW8pVK6/qcuwDbrdndeJr1AdGTqwVoH7IVstNemN+vu2JIaSQSlAQWQGFuX6a6hCAiL1/ywG6K6Ub5r8xTcE1k="
        on:
          tags: true
        repo: mattbennett/nameko-worker-postmortem
        distributions: "sdist bdist_wheel"
        skip_upload_docs: true

script:
  - tox -e $TOX_ENV
